import type { Metadata } from "next";
import Nav from '../components/Nav'
import Provider from './providers'
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Nav/>
        <main className="pt-16">{children}</main>
        </Provider>
      </body>
    </html>
  );
}
