import type { Metadata } from "next";
import Link from 'next/link'
import Provider from './providers'
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
       <nav className="bg-gray-800 text-white px-6 py-4 flex justify-between items-center sticky top-0 z-50 shadow">
          <div className="text-lg font-bold">
            MyApp
          </div>
          <div className="space-x-4">
            <Link href="/" className="hover:text-gray-300">
              Home
            </Link>
            <Link href="/about" className="hover:text-gray-300">
              About
            </Link>
            <Link href="/countries" className="hover:text-gray-300">
              Countries
            </Link>
            <Link href="/boards" className="hover:text-gray-300">
              Boards
            </Link>
          </div>
        </nav>
       {children}
        </Provider>
      </body>
    </html>
  );
}
